server:
  port: 8080

spring:
  application:
    name: downloader
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/szms-o2o?useUnicode=true&characterEncoding=UTF8
    username: root
    password:
